[build]
# Static files from this folder will be served at the root of the site.
publish = "apps/flower-care-netlify/public"
functions = "./functions"
command = "nx run flower-care-netlify:lint"

[functions]
# Directory with serverless functions, including background
# functions, to deploy. This is relative to the base directory
# if one has been set, or the root directory if
# a base hasn’t been set.
directory = "functions/"

# Specifies \`esbuild\` for functions bundling, esbuild is the default for TS
# node_bundler = "esbuild"

[functions."hello*"]
# Apply settings to any functions with a name beginning with "hello"

[functions."readings*"]
# Apply settings to any functions with a name beginning with "readings"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[dev]
  autoLaunch = false
  port = 8080 # The port that the netlify dev will be accessible on
