name: Flower-care-ci FE build and deploy

on:
  push:
    #branches:
    #  - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
    REGISTRY: ghcr.io

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read
  packages: write

jobs:
  build-with-docker-engine:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - uses: pnpm/action-setup@v2
          with:
            version: 8

        - uses: actions/setup-node@v4
          with:
            cache: 'pnpm'
            node-version-file: '.nvmrc'
            cache-dependency-path: 'pnpm-lock.yaml'

        - name: 'Install Dependencies'
          run: pnpm install --frozen-lockfile --prefer-frozen-lockfile --ignore-scripts

        - name: Derive appropriate SHAs for base and head for `nx affected` commands
          uses: nrwl/nx-set-shas@v3

        - name: 'Nx Build'
          run: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --configuration=production --parallel=2
        
        - name: GitHub Pages action
          # https://github.com/marketplace/actions/github-pages-action
          uses: peaceiris/actions-gh-pages@v3
          with:
            # Set a generated GITHUB_TOKEN for pushing to the remote branch.
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # Set an input directory for deployment.
            publish_dir: dist/apps/flower-care-fe
