on:
    workflow_call:

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
    actions: read
    contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - uses: pnpm/action-setup@v2
          with:
            version: 8

        - uses: actions/setup-node@v4
          with:
            cache: 'pnpm'
            node-version-file: '.nvmrc'
            cache-dependency-path: 'pnpm-lock.yaml'

        - name: 'Install Dependencies'
          run: pnpm install --frozen-lockfile --prefer-frozen-lockfile --ignore-scripts

        - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
          uses: nrwl/nx-set-shas@v3

        - name: 'Nx Build'
          run: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --configuration=production --parallel=2

        - name: 'Upload RPI Build Artifact'
          uses: actions/upload-artifact@v4
          with:
            name: flower-care-rpi-dist
            path: dist/apps/flower-care-rpi
            retention-days: 1
            if-no-files-found: error
            compression-level: 0 # no compression
    
        - name: 'Upload FE Build Artifact'
          uses: actions/upload-artifact@v4
          with:
            name: flower-care-fe-dist
            path: dist/apps/flower-care-fe
            retention-days: 1
            if-no-files-found: error
            compression-level: 0 # no compression
        