name: Flower-care-ci

on:
  push:
    #branches:
    #  - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
    REGISTRY: ghcr.io

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read
  packages: write

jobs:
  build-with-docker-engine:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log into registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - uses: actions/setup-node@v4
          with:
            cache: 'yarn'
            node-version-file: '.nvmrc'
            cache-dependency-path: 'yarn.lock'

        - name: 'Install node-gyp'
          run: yarn global add node-gyp

        - name: 'Install Dependencies'
          run: yarn install --frozen-lockfile

        - name: Derive appropriate SHAs for base and head for `nx affected` commands
          uses: nrwl/nx-set-shas@v3

        - name: 'Build'
          run: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --configuration=production --parallel=2
        
        - uses: docker/build-push-action@v5
          with:
            file: ./apps/flower-care-rpi/Dockerfile
            context: .
            push: true
            tags: "ghcr.io/battlefieldnoob/flower-care-rpi:pr-4"
            platforms: linux/arm64
            cache-from: type=gha
            cache-to: type=gha,mode=max
