on:
    workflow_call:

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
    actions: read
    contents: read
    packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: pnpm/action-setup@v2
          with:
            version: 8

        - uses: actions/setup-node@v4
          with:
            cache: 'pnpm'
            node-version-file: '.nvmrc'
            cache-dependency-path: 'pnpm-lock.yaml'

        - name: 'Install Dependencies'
          run: pnpm install --frozen-lockfile --prefer-frozen-lockfile --ignore-scripts

        - name: Derive appropriate SHAs for base and head for `nx affected` commands
          uses: nrwl/nx-set-shas@v3

        - name: 'Nx Build'
          run: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --configuration=production --parallel=2
        