name: Flower-care-ci

on:
  push:
    #branches:
    #  - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
    REGISTRY: ghcr.io

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read
  packages: write

jobs:
  build-with-docker-engine:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log into registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Derive appropriate SHAs for base and head for `nx affected` commands
          id: nx-shas
          uses: nrwl/nx-set-shas@v4

        - run: |
            echo "BASE: ${{ steps.nx-shas.outputs.base }}"
            echo "HEAD: ${{ steps.nx-shas.outputs.head }}"

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            # list of Docker images to use as base name for tags
            images: |
              ghcr.io/battlefieldnoob/flower-care-rpi           
            # generate Docker tags based on the following events/attributes
            tags: |
              "type=schedule",
              "type=ref,event=branch",
              "type=ref,event=tag",
              "type=ref,event=pr",
              "type=sha,prefix=sha-",
              "type=semver,pattern={{version}}",
              "type=semver,pattern={{major}}.{{minor}}",
              "type=semver,pattern={{major}}"
        
        - uses: docker/build-push-action@v5
          with:
            file: ./apps/flower-care-rpi/Dockerfile
            context: .
            push: true
            platforms: linux/arm64
            cache-from: type=gha
            cache-to: type=gha,mode=max
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              NX_BASE=${{ steps.nx-shas.outputs.base }}
              NX_HEAD=${{ steps.nx-shas.outputs.head }}
              CONFIG=production
