name: Flower-care-ci

on:
  push:
    #branches:
    #  - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
    REGISTRY: ghcr.io

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read
  packages: write

jobs:
  flower-care-rpi-build-and-deploy-docker:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: NX build
          uses: ./.github/workflows/flower-care-nx-build.yml
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log into registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: 'Docker meta'
          id: meta
          uses: docker/metadata-action@v5
          with:
            # list of Docker images to use as base name for tags
            images: |
              ghcr.io/battlefieldnoob/flower-care-rpi           
            # generate Docker tags based on the following events/attributes
            tags: |
              "type=schedule",
              "type=ref,event=branch",
              "type=ref,event=tag",
              "type=ref,event=pr",
              "type=sha,prefix=sha-",
              "type=semver,pattern={{version}}",
              "type=semver,pattern={{major}}.{{minor}}",
              "type=semver,pattern={{major}}"
        
        - uses: docker/build-push-action@v5
          with:
            file: ./apps/flower-care-rpi/Dockerfile
            context: .
            push: true
            platforms: linux/arm64
            cache-from: type=gha
            cache-to: type=gha,mode=max
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

  flower-care-fe-build-and-deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: NX build
          uses: ./.github/workflows/flower-care-nx-build.yml

        - name: GitHub Pages action
          # https://github.com/marketplace/actions/github-pages-action
          uses: peaceiris/actions-gh-pages@v3
          with:
            # Set a generated GITHUB_TOKEN for pushing to the remote branch.
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # Set an input directory for deployment.
            publish_dir: dist/apps/flower-care-fe
