name: Flower-care-ci

on:
  push:
    #branches:
    #  - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
    REGISTRY: ghcr.io

permissions:
  actions: read
  contents: read

jobs:
  flower-care-nx-build:
    uses: ./.github/workflows/flower-care-nx-build.yml

  flower-care-rpi-build-push-docker:
    runs-on: ubuntu-latest
    needs: flower-care-nx-build
    permissions:
      packages: write
    steps:
        - name: Download build results
          uses: actions/download-artifact@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log into registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: 'Docker meta'
          id: meta
          uses: docker/metadata-action@v5
          with:
            # list of Docker images to use as base name for tags
            images: |
              ghcr.io/battlefieldnoob/flower-care-rpi           
            # generate Docker tags based on the following events/attributes
            tags: |
              "type=schedule",
              "type=ref,event=branch",
              "type=ref,event=tag",
              "type=ref,event=pr",
              "type=sha,prefix=sha-",
              "type=semver,pattern={{version}}",
              "type=semver,pattern={{major}}.{{minor}}",
              "type=semver,pattern={{major}}"
        
        - uses: docker/build-push-action@v5
          with:
            # dist folder is omitted when downloading build results
            file: apps/flower-care-rpi/Dockerfile
            context: .
            push: true
            platforms: linux/arm64
            cache-from: type=gha
            cache-to: type=gha,mode=max
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

  flower-care-fe-deploy-github-pages:
    runs-on: ubuntu-latest
    needs: flower-care-nx-build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write
    steps:
        - name: Download build results
          uses: actions/download-artifact@v4

        - name: GitHub Pages action
            # https://github.com/marketplace/actions/github-pages-action
          uses: peaceiris/actions-gh-pages@v3
          with:
            # Set a generated GITHUB_TOKEN for pushing to the remote branch.
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # Set an input directory for deployment.
            # dist folder is omitted when downloading build results
            publish_dir: apps/flower-care-fe
